-- require("lspconfig").lua_ls.setup({
--   settings = {
--     Lua = {
--       hint = {
--         enable = true, -- necessary
--       }
--     }
--   }
-- })
--
-- require("lspconfig.configs").vtsls = require("vtsls").lspconfig
-- require('lspconfig').vtsls.setup {
--   -- capabilities = capabilities,
--   -- flags = lsp_flags,
--   -- on_attach = on_attach,
--   settings = {
--     typescript = {
--       inlayHints = {
--         parameterNames = { enabled = 'all' },
--         parameterTypes = { enabled = true },
--         variableTypes = { enabled = true },
--         propertyDeclarationTypes = { enabled = true },
--         functionLikeReturnTypes = { enabled = true },
--         enumMemberValues = { enabled = true },
--       },
--     },
--   },
-- }
--
-- require("lspconfig").zls.setup({
--   settings = {
--     zls = {
--       enable_inlay_hints = true,
--       inlay_hints_show_builtin = true,
--       inlay_hints_exclude_single_argument = true,
--       inlay_hints_hide_redundant_param_names = false,
--       inlay_hints_hide_redundant_param_names_last_token = false,
--     },
--   }
-- })
